import {addCreator,createRequest,decideRequest,loadState,markLive,saveState} from './ledger.js'

let {root,app}=loadState()
const $=id=>document.getElementById(id)
const esc=value=>String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))

function render(){({root,app}=loadState());$('wallet-available').textContent=app.wallet.available;$('wallet-card-available').textContent=app.wallet.available;$('wallet-locked').textContent=app.wallet.locked;$('wallet-earned').textContent=app.wallet.earned;$('wallet-requests').textContent=app.requests.length
  $('creator-grid').innerHTML=app.creators.map(c=>`<article class="creator-card"><div class="creator-mark">${esc(c.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2))}</div><span class="claim">${c.claim==='unclaimed'?'UNCLAIMED DIRECTORY':'LOCAL PROFILE'}</span><h3>${esc(c.name)}</h3><small>${esc(c.handle)}</small><p>${esc(c.bio)}</p><div class="tags">${c.topics.map(t=>`<span>${esc(t)}</span>`).join('')}</div><button class="request-creator secondary button" data-creator="${esc(c.id)}">Request service</button></article>`).join('')
  $('request-creator').innerHTML=app.creators.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')
  $('ledger-list').innerHTML=app.requests.length?app.requests.map(r=>`<article class="ledger-item"><div class="ledger-main"><span class="state state-${esc(r.status)}">${esc(r.status)}</span><h3>${esc(r.title)}</h3><p>${esc(r.purpose)}</p><div class="ledger-meta"><span>Creator: ${esc(r.creatorName)}</span>${r.product?`<span>Product: ${esc(r.product)}</span>`:''}${r.tags.map(t=>`<span>#${esc(t)}</span>`).join('')}</div></div><div class="ledger-actions">${r.status==='requested'?`<button data-action="accept" data-id="${r.id}">Accept</button><button data-action="decline" data-id="${r.id}">Decline</button>`:''}${r.status==='accepted'?`<button data-action="live" data-id="${r.id}">Go live</button>`:''}</div></article>`).join(''):`<div class="empty"><b>No service requests yet.</b><p>Create one above. Its purpose and creator decision will appear here.</p></div>`
}

document.addEventListener('click',event=>{const creator=event.target.closest('[data-creator]');if(creator){$('request-creator').value=creator.dataset.creator;location.hash='request'}const action=event.target.closest('[data-action]');if(action){try{action.dataset.action==='live'?markLive(root,action.dataset.id):decideRequest(root,action.dataset.id,action.dataset.action==='accept'?'accepted':'declined');render()}catch(e){alert(e.message)}}})
$('request-form').addEventListener('submit',event=>{event.preventDefault();try{const r=createRequest(root,{creatorId:$('request-creator').value,title:$('request-title').value,purpose:$('request-purpose').value,potential:$('request-potential').value,product:$('request-product').value,tags:$('request-tags').value,spaceLink:$('request-link').value});event.target.reset();$('request-status').textContent=`Request ${r.id} created. One Infinity service unit is locked until ${r.creatorName} decides.`;render()}catch(e){$('request-status').textContent=e.message}})
$('open-creator').addEventListener('click',()=> $('creator-dialog').showModal())
$('creator-form').addEventListener('submit',event=>{event.preventDefault();try{addCreator(root,{name:$('creator-name').value,handle:$('creator-handle').value,bio:$('creator-bio').value,topics:$('creator-topics').value});$('creator-dialog').close();event.target.reset();render()}catch(e){alert(e.message)}})
$('export-ledger').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(app,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='bitcoin-tonight-infinity-service-ledger.json';a.click();URL.revokeObjectURL(url)})
render()
