import test from 'node:test'
import assert from 'node:assert/strict'
import {APP_KEY,WALLET_KEY,addCreator,createRequest,decideRequest,freshAppState,loadState,markLive} from '../js/ledger.js'
const memory=()=>{const m=new Map;return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)}}
function setup(){const storage=memory();storage.setItem(WALLET_KEY,JSON.stringify({apps:{[APP_KEY]:freshAppState()}}));return{storage,...loadState(storage)}}
test('service request locks one Infinity unit without a changing quote',()=>{const x=setup();const r=createRequest(x.root,{creatorId:'jaimie',title:'Tonight Space',purpose:'Entertain and discuss ideas'},x.storage);assert.equal(r.units,1);const state=loadState(x.storage).app;assert.equal(state.wallet.available,9);assert.equal(state.wallet.locked,1)})
test('creator acceptance moves the locked unit to creator earnings',()=>{const x=setup();const r=createRequest(x.root,{creatorId:'fred',title:'Live talk',purpose:'Community entertainment'},x.storage);decideRequest(x.root,r.id,'accepted',x.storage);const app=loadState(x.storage).app;assert.equal(app.wallet.locked,0);assert.equal(app.wallet.earned,1);assert.equal(app.requests[0].status,'accepted')})
test('decline returns the service unit',()=>{const x=setup();const r=createRequest(x.root,{creatorId:'darkside',title:'Night talk',purpose:'Late discussion'},x.storage);decideRequest(x.root,r.id,'declined',x.storage);const app=loadState(x.storage).app;assert.equal(app.wallet.available,10);assert.equal(app.wallet.locked,0)})
test('only an accepted request may go live',()=>{const x=setup();const r=createRequest(x.root,{creatorId:'dj-vertigo',title:'Music Space',purpose:'Live set'},x.storage);assert.throws(()=>markLive(x.root,r.id,x.storage));decideRequest(x.root,r.id,'accepted',x.storage);markLive(x.root,r.id,x.storage);assert.equal(loadState(x.storage).app.requests[0].status,'live')})
test('creator can add an unverified local profile',()=>{const x=setup();const c=addCreator(x.root,{name:'New Creator',bio:'Creates conversations',topics:'talk, fun'},x.storage);assert.equal(c.claim,'local-unverified');assert.equal(loadState(x.storage).app.creators.at(-1).name,'New Creator')})
